name: Test .NET features

on:
  push:
    branches-ignore:
      - 'skip-ci/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration: ['Debug', 'Release']

    env:
      DOTNET_VERSION: '6.0.*'
      DOTNET_CONFIGURATION: ${{ matrix.configuration }}
      WORKING_DIR: ./tests/AppContext.Tests.csproj
      MONGODB_VERSION: '6.0'
      TestMongoDBConnectionString: 'mongodb://127.0.0.1:27017/appcontext-test'
      TestMongoDBDatabaseName: 'appcontext-test'

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Show project directory
        run: ls -lah
        working-directory: ${{ env.WORKING_DIR }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ env.MONGODB_VERSION }}

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ env.WORKING_DIR }}

      - name: Build project
        run: dotnet build --no-restore --configuration ${{ env.DOTNET_CONFIGURATION }}
        working-directory: ${{ env.WORKING_DIR }}

      - name: Run tests
        run: dotnet test ${{ matrix.project.test }} --no-build --no-restore --configuration ${{ env.DOTNET_CONFIGURATION }} --verbosity normal
        working-directory: ${{ env.WORKING_DIR }}
