name: Test .NET features

on:
  push:
    branches-ignore:
      - 'skip-ci/**'
    paths-ignore:
      - 'frontend/**'
      - 'doc/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration: ['Debug', 'Release']

    env:
      DOTNET_VERSION: '6.0.x'
      DOTNET_CONFIGURATION: ${{ matrix.configuration }}
      TEST_PROJECT: ./tests/Appcontext.Tests.csproj
      MONGODB_VERSION: '6.0'
      TestMongoDBConnectionString: 'mongodb://127.0.0.1:27017/appcontext-test'
      TestMongoDBDatabaseName: 'appcontext-test'

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ env.MONGODB_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration ${{ env.DOTNET_CONFIGURATION }}

      - name: Run tests
        run: dotnet test ${{ env.TEST_PROJECT }} --no-build --no-restore --configuration ${{ env.DOTNET_CONFIGURATION }} --verbosity normal
